export const ADDRESS_COLUMN_MAPPINGS = {
  address: [
    'address',
    'street',
    'street_address',
    'location_address',
    'location_street',
    'dirección',
    'Address Line1',
  ],
  postcode: [
    'postcode',
    'zip',
    'zipcode',
    'zip_code',
    'location_postcode',
    'location_zip',
    'location_zipcode',
    'código postal',
    'cp',
    'address postal code',
  ],
  city: [
    'city',
    'town',
    'population',
    'population_city',
    'population_town',
    'población',
    'address city',
  ],
  province: [
    'province',
    'state',
    'county',
    'region',
    'location_province',
    'location_state',
    'location_county',
    'location_region',
    'provincia',
    'address state',
  ],
  country: [
    'country',
    'country_code',
    'location_country',
    'location_country_code',
    'país',
  ],
};